# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dfd12d576ff22c8696f6cd370c3b7370050461229078f406dd11222392abe8a7ce5cedb3feec788fe8465624905f1e178db2546c2d353056ee4250baf29d1b0

test:
  secret_key_base: c25f3e972cce488d4ae666faaa58b4eebb021dfaf4c8a3124cd5d02950c5c0b146fd2597b25c74c70b7d2146848c47363d8147767ef651d2d63c99ba2661c17b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
